baseURL: https://metakits.cc/PicoArt/
languageCode: ko-kr
defaultContentLanguage: ko
title: Pico Art
theme: cupper-hugo-theme
publishDir: docs

# googleAnalytics: UA-123456789-1
# disqusShortname: yourdiscussshortname

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Digital arts in the very small form.
  homeMetaContent:
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser

menu:
  nav:
    - name: About
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: RSS
      url: /index.xml
      weight: 3
    - name: Artworks
      url: /post/
      weight: 4
  picoarts:
    - name: 10PRINT
      url: /10print/
      weight: 1
